# Heroku doesn't seem to fully support multi-stage builds yet
FROM golang:1.12.7-alpine

# Install Git so `go get` works
RUN apk add --no-cache git
# Install the Certificate-Authority certificates to enable HTTPS
RUN apk add --no-cache ca-certificates

WORKDIR $GOPATH/src/github.com/jessemillar/butler-lewis
COPY ./ .
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix nocgo -o /app .

CMD ["/app"]
